# Generated by Django 6.0.5 on 2026-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='visivel_para_o_cliente',
            field=models.BooleanField(default=True, verbose_name='Visível para o cliente'),
        ),
    ]
