# Generated by Django 6.0.5 on 2026-05-26 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendamento_visivel_para_o_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Barbeiro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para Agendamentos')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.RemoveField(
            model_name='servico',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(default='Sem descrição', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.IntegerField(verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profissional', verbose_name='Barbeiro'),
        ),
    ]
